WellCommerce\Bundle\PaymentBundle\Entity\Payment:
    type: entity
    table: payment
    repositoryClass: WellCommerce\Bundle\PaymentBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        processor:
            type: string
            nullable: false
            length: 64
        configuration:
            type: json_array
        comment:
            type: string
            length: 1000
            nullable: true
        state:
            type: string
            nullable: false
            length: 64
        token:
            type: guid
            nullable: false
            unique: true
            length: 255
        externalIdentifier:
            type: string
            nullable: true
            length: 255
        externalToken:
            type: string
            nullable: true
            length: 255
        redirectUrl:
            type: string
            nullable: true
            length: 255
    oneToMany:
        paymentStateHistory:
            targetEntity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentStateHistory
            cascade:
                - persist
            fetch: LAZY
            mappedBy: payment
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            inversedBy: payments
            joinColumn:
                name: order_id
                referencedColumnName: id
                onDelete: CASCADE
