WellCommerce\Bundle\PaymentBundle\Entity\Payment:
    type: entity
    table: payment
    repositoryClass: WellCommerce\Bundle\PaymentBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        processor:
            type: string
            nullable: false
            length: 64
        token:
            type: string
            nullable: true
            length: 255
        configuration:
            type: json_array
        state:
            type: string
            nullable: true
            length: 64
        approvalUrl:
            type: string
            nullable: true
            length: 255
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            inversedBy: payments
            joinColumn:
                name: order_id
                referencedColumnName: id
                onDelete: CASCADE
