doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodInterface: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod

well_commerce_payment:
    configuration:
        payment:
            orm:
                manager: WellCommerce\Bundle\PaymentBundle\Manager\PaymentManager
                factory: WellCommerce\Bundle\PaymentBundle\Factory\PaymentFactory
                repository: WellCommerce\Bundle\PaymentBundle\Repository\PaymentRepository
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/Payment.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\Payment
        payment_state_history:
            orm:
                manager: WellCommerce\Bundle\PaymentBundle\Manager\PaymentStateHistoryManager
                factory: WellCommerce\Bundle\PaymentBundle\Factory\PaymentStateHistoryFactory
                repository: WellCommerce\Bundle\PaymentBundle\Repository\PaymentStateHistoryRepository
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/PaymentStateHistory.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentStateHistory
        payment_method:
            orm:
                factory: WellCommerce\Bundle\PaymentBundle\Factory\PaymentMethodFactory
                repository: WellCommerce\Bundle\PaymentBundle\Repository\PaymentMethodRepository
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/PaymentMethod.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod
            api:
                exposed: true
                dataset: payment_method.dataset.admin
                manager: payment_method.manager
        payment_method_translation:
            orm:
                manager: false
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/PaymentMethodTranslation.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodTranslation

well_commerce_locale:
    copier:
        entities:
            WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodTranslation:
                properties:
                    - name
