WellCommerce\Bundle\PaymentBundle\Entity\Payment:
    fields:
        id:
            groups:
                - default
                - payment
        processor:
            groups:
                - default
                - payment
        configuration:
            groups:
                - default
                - payment
        comment:
            groups:
                - default
                - payment
        state:
            groups:
                - default
                - payment
        token:
            groups:
                - default
                - payment
        externalIdentifier:
            groups:
                - default
                - payment
        externalToken:
            groups:
                - default
                - payment
        redirectUrl:
            groups:
                - default
                - payment
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        paymentStateHistory:
            groups:
                - payment
        order:
            groups:
                - payment
    callbacks: {  }
