WellCommerce\Bundle\PaymentBundle\Entity\PaymentStateHistory:
    fields:
        id:
            groups:
                - default
                - payment_state_history
        state:
            groups:
                - default
                - payment_state_history
        comment:
            groups:
                - default
                - payment_state_history
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        payment:
            groups:
                - payment_state_history
        createdBy:
            groups:
                - payment_state_history
        updatedBy:
            groups:
                - payment_state_history
        deletedBy:
            groups:
                - payment_state_history
    callbacks: {  }
