WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod:
    fields:
        id:
            groups:
                - default
                - payment_method
        enabled:
            groups:
                - default
                - payment_method
        hierarchy:
            groups:
                - default
                - payment_method
        processor:
            groups:
                - default
                - payment_method
        configuration:
            groups:
                - default
                - payment_method
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        paymentPendingOrderStatus:
            groups:
                - payment_method
        paymentSuccessOrderStatus:
            groups:
                - payment_method
        paymentFailureOrderStatus:
            groups:
                - payment_method
        shippingMethods:
            groups:
                - payment_method
        createdBy:
            groups:
                - payment_method
        updatedBy:
            groups:
                - payment_method
        deletedBy:
            groups:
                - payment_method
        translations:
            groups:
                - payment_method
    callbacks: {  }
